# SPDX-FileCopyrightText: Copyright (c) 2026 Maulik Mistry
# SPDX-License-Identifier: Apache-2.0
#
# cachyos_paritions.conf - CachyOS default partition and mapping setup paths.
#
# Author: Maulik Mistry
# Please share support: https://www.paypal.com/paypalme/m1st0
#                       https://venmo.com/code?user_id=3319592654995456106&created=1753283702

CACHYOS_LUKS="/dev/sda6"
CACHYOS_MAPPER="cachyos"
CACHYOS_MAIN="/dev/mapper/$CACHYOS_MAPPER"
CACHYOS_BOOT="/dev/sda5"
CACHYOS_MOUNT="/media/internal_drive"

